- name: criando o nosso cenario de micro servicos
  hosts: docker
  tasks:
    - name: create container
      docker_container:
       name: rabbit_jorge
       image: httpd
       state: started
       ports:
        - 8082:80
       volumes:
        - /index:/user/local/apache2/htdocs

    - name: download repository
      git:
       repo: http://devops.dexter.com.br/root/docker
       dest: /index/
