- name: remove apache2 and install nginx
  hosts: docker
  tasks:
    - name: stop apache2
      service:
       name: apache2
       state: stopped
  
    - name: remove apache2
      package:
       name: apache2
       state: absent

    - name: install nginx
      package:
       name: nginx
       state: present
       update_cache: yes
