
#- name: install puppet5
- name: install Puppet5
  package:
   name:
    - puppetserver
   state: present
   update_cache: yes
  when:
   - ansible_hostname == "devops"

- name: install Puppet5
  package:
   name:
    - puppet-agent
   state: present
   update_cache: yes
  when:
   - ansible_os_family == "Debian" or ansible_os_family == "RedHat"
