- name: install packages
  package:
   name: 
    - nginx
    - python-pip
    - docker-ce
   state: present
   update_cache: yes

- name: install docker-py
  pip:
    name: docker-py
    state: present
